### ISSUE TITLE
panicparse mangles cgo stack traces.

### ISSUE THREAD

**Issue by mberhault** [maruel/panicparse#21]
We have a cgo call in our log that gets slightly mangled by panic parse:
From the raw log:
```
goroutine 56 [runnable, locked to thread]: 
github.com/cockroachdb/cockroach/storage/engine._Cfunc_DBIterSeek(0x7f147f5fc2c0, 0xc82996fd80, 0x10, 0x0, 0x0, 0xc820024801, 0x7f14089fbc88, 0xc800000010, 0x0, 0xc800000000, ...)
  ??:0 +0x6d
github.com/cockroachdb/cockroach/storage/engine.(*rocksDBIterator).Seek(0xc8465534a0, 0xc82996fd80, 0x10, 0x20, 0x0, 0xc800000000)
  /go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:634 +0x421
github.com/cockroachdb/cockroach/storage/engine.MVCCIterate(0x7f15818a6400, 0xc82028bd40, 0xc82996fd80, 0x10, 0x20, 0xc82996fda0, 0x10, 0x20, 0x0, 0x0, ...)
  /go/src/github.com/cockroachdb/cockroach/storage/engine/mvcc.go:1266 +0x131d
github.com/cockroachdb/cockroach/storage.(*Replica).entries(0xc82053aa80, 0x7f15818a6400, 0xc82028bd40, 0xe2ff0, 0xe2ff1, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, ...)
  /go/src/github.com/cockroachdb/cockroach/storage/replica_raftstorage.go:120 +0x436
github.com/cockroachdb/cockroach/storage.(*Replica).Entries(0xc82053aa80, 0xe2ff0, 0xe2ff1, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
  /go/src/github.com/cockroachdb/cockroach/storage/replica_raftstorage.go:86 +0xa7
github.com/coreos/etcd/raft.(*raftLog).slice(0xc820e6f880, 0xe2ff0, 0xe2ff1, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
  /go/src/github.com/coreos/etcd/raft/log.go:307 +0x195
github.com/coreos/etcd/raft.(*raftLog).nextEnts(0xc820e6f880, 0x0, 0x0, 0x0)
  /go/src/github.com/coreos/etcd/raft/log.go:142 +0x9f
github.com/coreos/etcd/raft.newReady(0xc827880300, 0xc8462a1070, 0xb, 0x4, 0xe2fef, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  /go/src/github.com/coreos/etcd/raft/node.go:475 +0x70
github.com/coreos/etcd/raft.(*RawNode).newReady(0xc833b899c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  /go/src/github.com/coreos/etcd/raft/rawnode.go:40 +0x60
github.com/coreos/etcd/raft.(*RawNode).Ready(0xc833b899c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  /go/src/github.com/coreos/etcd/raft/rawnode.go:182 +0x43
github.com/cockroachdb/cockroach/storage.(*Replica).handleRaftReady(0xc82053aa80, 0x0, 0x0)
  /go/src/github.com/cockroachdb/cockroach/storage/replica.go:1167 +0x10e
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
  /go/src/github.com/cockroachdb/cockroach/storage/store.go:1802 +0x35a
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202b0e00, 0xc820209300)
  /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
  /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
```

After running through the latest panicparse (no args), I get the following slightly-truncated trace at the very beginning of the generated output (eg: before the other goroutines in panicparse's output):
```
  ??:0 +0x6d
github.com/cockroachdb/cockroach/storage/engine.(*rocksDBIterator).Seek(0xc8465534a0, 0xc82996fd80, 0x10, 0x20, 0x0, 0xc800000000)
  /go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:634 +0x421
github.com/cockroachdb/cockroach/storage/engine.MVCCIterate(0x7f15818a6400, 0xc82028bd40, 0xc82996fd80, 0x10, 0x20, 0xc82996fda0, 0x10, 0x20, 0x0, 0x0, ...)
  /go/src/github.com/cockroachdb/cockroach/storage/engine/mvcc.go:1266 +0x131d
github.com/cockroachdb/cockroach/storage.(*Replica).entries(0xc82053aa80, 0x7f15818a6400, 0xc82028bd40, 0xe2ff0, 0xe2ff1, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, ...)
  /go/src/github.com/cockroachdb/cockroach/storage/replica_raftstorage.go:120 +0x436
github.com/cockroachdb/cockroach/storage.(*Replica).Entries(0xc82053aa80, 0xe2ff0, 0xe2ff1, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
  /go/src/github.com/cockroachdb/cockroach/storage/replica_raftstorage.go:86 +0xa7
github.com/coreos/etcd/raft.(*raftLog).slice(0xc820e6f880, 0xe2ff0, 0xe2ff1, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
  /go/src/github.com/coreos/etcd/raft/log.go:307 +0x195
github.com/coreos/etcd/raft.(*raftLog).nextEnts(0xc820e6f880, 0x0, 0x0, 0x0)
  /go/src/github.com/coreos/etcd/raft/log.go:142 +0x9f
github.com/coreos/etcd/raft.newReady(0xc827880300, 0xc8462a1070, 0xb, 0x4, 0xe2fef, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  /go/src/github.com/coreos/etcd/raft/node.go:475 +0x70
github.com/coreos/etcd/raft.(*RawNode).newReady(0xc833b899c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  /go/src/github.com/coreos/etcd/raft/rawnode.go:40 +0x60
github.com/coreos/etcd/raft.(*RawNode).Ready(0xc833b899c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  /go/src/github.com/coreos/etcd/raft/rawnode.go:182 +0x43
github.com/cockroachdb/cockroach/storage.(*Replica).handleRaftReady(0xc82053aa80, 0x0, 0x0)
  /go/src/github.com/cockroachdb/cockroach/storage/replica.go:1167 +0x10e
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
  /go/src/github.com/cockroachdb/cockroach/storage/store.go:1802 +0x35a
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202b0e00, 0xc820209300)
  /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
  /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
```
And the following entry corresponding to the beginning of the actual trace:
```
1: runnable [locked]
    engine         .:0                     _Cfunc_DBIterSeek(#470, #429, 0x10, 0, 0, #77, #469, #56, 0, #4, ...)
```

Please find attached the full logs. This is from https://github.com/cockroachdb/cockroach and covers the entire lifetime of that process.
Full log:
[node0.log.txt](https://github.com/maruel/panicparse/files/176687/node0.log.txt)

Output from `cat node0.log.txt | pp > node0.parsed-plain.txt`
[node0.parsed-plain.txt](https://github.com/maruel/panicparse/files/176689/node0.parsed-plain.txt)

**Comment by maruel** [comment]
Thanks for the report! I had never seen `??:0` before, I'll have to loook where it's getting generated then will update stack/stack.go. You can try sending a PR that adjust the regexp in this line. Otherwise it may take a moment as I'm a bit overloaded this week.

**Comment by mberhault** [comment]
same here, lots of cockroach work going on, but I can take a crack at it. Either way, there's no particular rush.
