### ISSUE TITLE
"no input file specified" error

### ISSUE THREAD

**Issue by mpmlj** [maruel/panicparse#28]
Hi,

Trying to debug one panicing test on Mac OS Sierra, Go 1.8, via Terminal 2 (also installed bash v4 -  with the same result), but getting "/usr/bin/pp5.18: No input files specified" whatever I do.

```Go
myuser: ~/go/src/mydirectory $ go test --tags all --run TestExtractUserIDFromReqToken -v 2>&1 | pp
Creating tables and indexes...
Done.

TOTAL TIME: 0.83 sec.
=== RUN   TestExtractUserIDFromReqToken
--- FAIL: TestExtractUserIDFromReqToken (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x17c767c]

goroutine 21 [running]:
testing.tRunner.func1(0xc42031c340)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x18dc760, 0x1ec7fe0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
blah-blah/usersvc.TestExtractUserIDFromReqToken(0xc42031c340)
	/Users/myuser/go/src/blah-blah/testfile.go:20 +0x5c
testing.tRunner(0xc42031c340, 0x1a176c8)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca
exit status 2
FAIL	blah-blah	0.877s
**/usr/bin/pp5.18: No input files specified**
```

Please let me know if I'm using arguments correctly?
Thank you!!

**Comment by maruel** [comment]
https://github.com/maruel/panicparse#if-you-have-usrbinpp-installed

**Comment by mpmlj** [comment]
@maruel 
Thank you!! That was my issue.

**Comment by maruel** [comment]
Clarified README.md to include the error strings. Hopefully other users who hit this will have a better chance to figure out what happened.
