### ISSUE TITLE
pp panics on accessing array index out of range

### ISSUE THREAD

**Issue by TrueFurby** [maruel/panicparse#38]
Running `pp` with output from my long running process panics here: 
https://github.com/maruel/panicparse/blob/f6ee1e454807f72b84277a84fc06437081340a1b/stack/source.go#L139

```sh
$ curl https://gist.githubusercontent.com/TrueFurby/27e50782a159ee8191774b230bd377af/raw/1b043460b3333b2c5d125cf7e694927da44167c5/gistfile1.txt | pp
```

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/maruel/panicparse/stack.(*parsedFile).getFuncAST.func1(0x5db100, 0xc420077c80, 0xc420418b00)
	/home/furby/go/src/github.com/maruel/panicparse/stack/source.go:139 +0x14c
go/ast.inspector.Visit(0xc42054c700, 0x5db100, 0xc420077c80, 0x0, 0x0)
	/usr/local/go/src/go/ast/walk.go:373 +0x3a
go/ast.Walk(0x5da4c0, 0xc42054c700, 0x5db100, 0xc420077c80)
	/usr/local/go/src/go/ast/walk.go:52 +0x66
go/ast.Inspect(0x5db100, 0xc420077c80, 0xc42054c700)
	/usr/local/go/src/go/ast/walk.go:385 +0x4b
github.com/maruel/panicparse/stack.(*parsedFile).getFuncAST(0xc42051ec60, 0xc42010d484, 0xf, 0x1ae, 0xc4200c5820)
	/home/furby/go/src/github.com/maruel/panicparse/stack/source.go:129 +0x103
github.com/maruel/panicparse/stack.(*cache).getFuncAST(0xc4200bfb18, 0xc42014c720, 0x0)
	/home/furby/go/src/github.com/maruel/panicparse/stack/source.go:105 +0xb2
github.com/maruel/panicparse/stack.(*cache).augmentGoroutine(0xc4200bfb18, 0xc42020a5c0)
	/home/furby/go/src/github.com/maruel/panicparse/stack/source.go:58 +0x107
github.com/maruel/panicparse/stack.Augment(0xc42020a000, 0xc0, 0x10b)
	/home/furby/go/src/github.com/maruel/panicparse/stack/source.go:34 +0x5a
github.com/maruel/panicparse/internal.process(0x5da380, 0xc42000c010, 0x5da3c0, 0xc42000c018, 0x5ee300, 0x2, 0x100, 0xc42003fef0, 0x4f5cef)
	/home/furby/go/src/github.com/maruel/panicparse/internal/main.go:67 +0x2ea
github.com/maruel/panicparse/internal.Main(0x0, 0x0)
	/home/furby/go/src/github.com/maruel/panicparse/internal/main.go:138 +0x3b5
main.main()
	/home/furby/go/src/github.com/maruel/panicparse/cmd/pp/main.go:27 +0x26

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [chan receive]:
github.com/maruel/panicparse/internal.Main.func1(0xc42005e1e0)
	/home/furby/go/src/github.com/maruel/panicparse/internal/main.go:93 +0x34
created by github.com/maruel/panicparse/internal.Main
	/home/furby/go/src/github.com/maruel/panicparse/internal/main.go:91 +0xa3

goroutine 7 [select, locked to thread]:
runtime.gopark(0x549340, 0x0, 0x5409fc, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:277 +0x12c
runtime.selectgo(0xc420040f50, 0xc42005e2a0)
	/usr/local/go/src/runtime/select.go:395 +0x1138
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:511 +0x220
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1
```

**Comment by maruel** [comment]
Thanks for the report. This can only be reproduces on a workstation with the sources of the crash you reported, since the crash is in the source parsing logic.

What I suspect it happens is that the sources currently in GOPATH do not exactly match the ones that were used to build the binaries. In particular, one source file is significantly shorter, so that the line number in the signature doesn't exist. I will fix this.

**Comment by maruel** [comment]
Can you `go get -u github.com/maruel/panicparse/cmd/pp` and confirm that at least it doesn't crash anymore? If this works I'll release v1.0.2.
