### ISSUE TITLE
Stack trace not printed

### ISSUE THREAD

**Issue by tzachshabtay** [maruel/panicparse#44]
This utility has worked great for us so far, but we had an incident in which panicparse not only failed to format and color the error, it also completely swallowed it.

i.e, with panicparse, we saw this error:
```
2019/04/15 17:39:51 http: panic serving [::1]:50141: string length out of range: -58
```

We had to reproduce without panicparse to see the actual stack trace:
```
2019/04/15 17:44:16 http: panic serving [::1]:50622: string length out of range: -58
goroutine 52 [running]:
net/http.(*conn).serve.func1(0xc000198000)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1769 +0x139
panic(0x4750f80, 0xc000246260)
        /usr/local/Cellar/go/1.12.1/libexec/src/runtime/panic.go:522 +0x1b5
apollo/micro/internal/tradeconv.ConvAction(0xc0002f40a0, 0x99, 0x99, 0xc00039e640)
        /Users/tshabtay/git/fleet/src/apollo/micro/internal/tradeconv/tradeconv.go:24 +0x21d
apollo/micro/svc/recon/internal/dates.(*API).DatesGet(0xc0002d48d0, 0x495b820, 0xc0005c2150, 0xc000318400, 0x13414cf, 0x4713720, 0x495b820)
        /Users/tshabtay/git/fleet/src/apollo/micro/svc/recon/internal/dates/api.go:50 +0xc29
apollo/micro/svc/recon/internal/restapi.HandlerAPI.func2(0xc000318400, 0x13414cf, 0x457a301, 0xc0001320a0)
        /Users/tshabtay/git/fleet/src/apollo/micro/svc/recon/internal/restapi/configure_recon.go:80 +0x65
apollo/micro/svc/recon/internal/restapi/operations/dates.DatesGetHandlerFunc.Handle(0xc000075540, 0xc000318400, 0x13414cf, 0x4948f00, 0xc0001320a0)
        /Users/tshabtay/git/fleet/src/apollo/micro/svc/recon/internal/restapi/operations/dates/dates_get.go:19 +0x3a
apollo/micro/svc/recon/internal/restapi/operations/dates.(*DatesGet).ServeHTTP(0xc0002a20c0, 0x49594e0, 0xc00039c1c0, 0xc000318400)
        /Users/tshabtay/git/fleet/src/apollo/micro/svc/recon/internal/restapi/operations/dates/dates_get.go:54 +0x16e
apollo/vendor/github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x49594e0, 0xc00039c1c0, 0xc000318400)
        /Users/tshabtay/git/fleet/src/apollo/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc0002d4150, 0x49594e0, 0xc00039c1c0, 0xc000318400)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1995 +0x44
apollo/vendor/github.com/go-openapi/runtime/middleware.NewRouter.func1(0x49594e0, 0xc00039c1c0, 0xc000318200)
        /Users/tshabtay/git/fleet/src/apollo/vendor/github.com/go-openapi/runtime/middleware/router.go:76 +0x358
net/http.HandlerFunc.ServeHTTP(0xc0002a31e0, 0x49594e0, 0xc00039c1c0, 0xc000318200)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1995 +0x44
apollo/vendor/github.com/go-openapi/runtime/middleware.Redoc.func1(0x49594e0, 0xc00039c1c0, 0xc000318200)
        /Users/tshabtay/git/fleet/src/apollo/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 +0x2a5
net/http.HandlerFunc.ServeHTTP(0xc000576a00, 0x49594e0, 0xc00039c1c0, 0xc000318200)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1995 +0x44
apollo/vendor/github.com/go-openapi/runtime/middleware.Spec.func1(0x49594e0, 0xc00039c1c0, 0xc000318200)
        /Users/tshabtay/git/fleet/src/apollo/vendor/github.com/go-openapi/runtime/middleware/spec.go:46 +0x1ad
net/http.HandlerFunc.ServeHTTP(0xc000576a40, 0x49594e0, 0xc00039c1c0, 0xc000318200)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1995 +0x44
apollo/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x49594e0, 0xc00039c1c0, 0xc000318200)
        /Users/tshabtay/git/fleet/src/apollo/vendor/github.com/rs/cors/cors.go:207 +0x1af
net/http.HandlerFunc.ServeHTTP(0xc0002a3a00, 0x49594e0, 0xc00039c1c0, 0xc000318200)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1995 +0x44
net/http.serverHandler.ServeHTTP(0xc000345380, 0x49594e0, 0xc00039c1c0, 0xc000318200)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000198000, 0x495b760, 0xc0002381c0)
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.12.1/libexec/src/net/http/server.go:2884 +0x2f4
```

**Comment by maruel** [comment]
One question: did it contain a trailing LF? Because while panicparse is parsing the stack trace it is not printing anything as it will reformat the output, but it stops once it finds two consecutive LF.

**Comment by maruel** [comment]
Closing due to lack of reply from the reporter.
