### ISSUE TITLE
Failed to execute temporary parl

### ISSUE THREAD

**Issue by Antonboom** [maruel/panicparse#60]
Hello!

```
$ uname -a
Darwin MacBook-Pro.local 20.4.0 Darwin Kernel Version 20.4.0: 
Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101 arm64

$ go version
go version go1.16.4 darwin/arm64
```

```
$ cat panic.txt
panic: sky is falling

goroutine 17 [running]:
main.foo()
	/Users/anthony/gopanic/main.go:14 +0x38
created by main.main
	/Users/anthony/gopanic/main.go:8 +0x4c
exit status 2
```

```
$ pp panic.txt
Failed to execute temporary parl (class PAR::StrippedPARL::Static) in file 
'/var/folders/6t/v80c8sfs5zqf38b2yhzq592h0000gn/T/parlblFF': Inappropriate ioctl for device at 
/System/Library/Perl/Extras/5.30/PAR/StrippedPARL/Base.pm line 77, <DATA> line 1.
/usr/bin/pp5.30: Failed to extract a parl from 'PAR::StrippedPARL::Static' to file 
'/var/folders/6t/v80c8sfs5zqf38b2yhzq592h0000gn/T/parlsUtSZkL' at 
/System/Library/Perl/Extras/5.30/PAR/Packer.pm line 1216, <DATA> line 1.
```

**Comment by maruel** [comment]
See https://github.com/maruel/panicparse#if-you-have-usrbinpp-installed
