### ISSUE TITLE
Tests in ./stack fail on go1.17beta1

### ISSUE THREAD

**Issue by maruel** [maruel/panicparse#61]
Repro:

```
go get golang.org/dl/go1.17beta1
go1.17beta1 download
go1.17beta1 test ./stack
```

TestAugment and TestPanic fail.

**Comment by stapelberg** [comment]
Can reproduce. Output is:

```
--- FAIL: TestAugment (0.00s)
    --- FAIL: TestAugment/10-non-pointer_method (0.12s)
        source_test.go:552: First
        source_test.go:574: failed to parse input: failed to parse int on line: "main.S.f({})"
    --- FAIL: TestAugment/13-string_and_int (0.12s)
        source_test.go:552: First
        source_test.go:574: failed to parse input: failed to parse int on line: "main.f({0x4615a1, 0x459b60}, 0xc0000001a0)"
    --- FAIL: TestAugment/18-float64 (0.13s)
        source_test.go:552: First
        source_test.go:606: Different (-want +got):
              stack.Stack{
              	Calls: []stack.Call{
              		{
              			Func: {Complete: "main.f", ImportPath: "main", DirName: "main", Name: "f", ...},
              			Args: stack.Args{
              				Values:    {{Value: 824633721248, IsPtr: true}},
            - 				Processed: []string{"0.5"},
            + 				Processed: []string{"4.07423192071e-312"},
              				Elided:    false,
              			},
              			RemoteSrcPath: "/tmp/stack724483792/main.go",
              			Line:          6,
              			... // 6 identical fields
              		},
              		{Func: {Complete: "main.main", ImportPath: "main", DirName: "main", Name: "main", ...}, RemoteSrcPath: "/tmp/stack724483792/main.go", Line: 3, SrcName: "main.go", ...},
              	},
              	Elided: false,
              }
        source_test.go:607: Output:
            panic: ooh
            
            goroutine 1 [running]:
            main.f(0xc0000001a0)
            	/tmp/stack724483792/main.go:6 +0x27
            main.main()
            	/tmp/stack724483792/main.go:3 +0x25
            exit status 2
    --- FAIL: TestAugment/17-float32 (0.13s)
        source_test.go:552: First
        source_test.go:606: Different (-want +got):
              stack.Stack{
              	Calls: []stack.Call{
              		{
              			Func: {Complete: "main.f", ImportPath: "main", DirName: "main", Name: "f", ...},
              			Args: stack.Args{
              				Values: []stack.Arg{
              					{
            - 						Value: 805306367,
            + 						Value: 416,
              						Name:  "",
            - 						IsPtr: true,
            + 						IsPtr: false,
              					},
              				},
            - 				Processed: []string{"0.5"},
            + 				Processed: []string{"5.83e-43"},
              				Elided:    false,
              			},
              			RemoteSrcPath: "/tmp/stack1326545790/main.go",
              			Line:          6,
              			... // 6 identical fields
              		},
              		{Func: {Complete: "main.main", ImportPath: "main", DirName: "main", Name: "main", ...}, RemoteSrcPath: "/tmp/stack1326545790/main.go", Line: 3, SrcName: "main.go", ...},
              	},
              	Elided: false,
              }
        source_test.go:607: Output:
            panic: ooh
            
            goroutine 1 [running]:
            main.f(0x1a0)
            	/tmp/stack1326545790/main.go:6 +0x27
            main.main()
            	/tmp/stack1326545790/main.go:3 +0x25
            exit status 2
    --- FAIL: TestAugment/0-Local_function_doesn't_interfere (0.15s)
        source_test.go:552: First
        source_test.go:606: Different (-want +got):
              stack.Stack{
              	Calls: []stack.Call{
              		{
              			Func: {Complete: "main.f", ImportPath: "main", DirName: "main", Name: "f", ...},
              			Args: stack.Args{
            - 				Values:    []stack.Arg{{Value: 805306367, IsPtr: true}, {Value: 2}},
            + 				Values:    nil,
            - 				Processed: []string{"string(0x2fffffff, len=2)"},
            + 				Processed: nil,
            - 				Elided:    false,
            + 				Elided:    true,
              			},
              			RemoteSrcPath: "/tmp/stack769799239/main.go",
              			Line:          10,
              			... // 6 identical fields
              		},
              		{Func: {Complete: "main.main", ImportPath: "main", DirName: "main", Name: "main", ...}, RemoteSrcPath: "/tmp/stack769799239/main.go", Line: 3, SrcName: "main.go", ...},
              	},
              	Elided: false,
              }
        source_test.go:607: Output:
            panic: ooh
            
            goroutine 1 [running]:
            main.f(...)
            	/tmp/stack769799239/main.go:10
            main.main()
            	/tmp/stack769799239/main.go:3 +0x3c
            exit status 2
    --- FAIL: TestAugment/14-values_are_elided (0.15s)
        source_test.go:552: First
        source_test.go:606: Different (-want +got):
              stack.Stack{
              	Calls: []stack.Call{
              		{
              			Func: {Complete: "main.f", ImportPath: "main", DirName: "main", Name: "f", ...},
              			Args: stack.Args{
              				Values: []stack.Arg{
            + 					{Value: 824634083152, IsPtr: true},
            + 					{Value: 824634083184, IsPtr: true},
            + 					{Value: 4212505, IsPtr: true},
            + 					{Value: 96},
              					{},
              					{},
              					{
            - 						Value: 0,
            + 						Value: 4269381,
              						Name:  "",
            - 						IsPtr: false,
            + 						IsPtr: true,
              					},
              					{
            - 						Value: 0,
            + 						Value: 4561760,
              						Name:  "",
            - 						IsPtr: false,
            + 						IsPtr: true,
              					},
              					{
            - 						Value: 0,
            + 						Value: 824633721248,
              						Name:  "",
            - 						IsPtr: false,
            + 						IsPtr: true,
              					},
            - 					{},
            - 					{},
            - 					{},
            - 					{Value: 42},
              					{Value: 43},
              				},
              				Processed: []string{
            + 					"824634083152",
            + 					"824634083184",
            + 					"4212505",
            + 					"96",
              					"0",
              					"0",
            - 					"0",
            + 					"4269381",
            - 					"0",
            + 					"4561760",
            - 					"0",
            + 					"824633721248",
            - 					"0",
            - 					"0",
            - 					"0",
            - 					"42",
              					"43",
              				},
              				Elided: true,
              			},
              			RemoteSrcPath: "/tmp/stack545513363/main.go",
              			Line:          6,
              			... // 6 identical fields
              		},
              		{Func: {Complete: "main.main", ImportPath: "main", DirName: "main", Name: "main", ...}, RemoteSrcPath: "/tmp/stack545513363/main.go", Line: 3, SrcName: "main.go", ...},
              	},
              	Elided: false,
              }
        source_test.go:607: Output:
            panic: ooh
            
            goroutine 1 [running]:
            main.f(0xc000058750, 0xc000058770, 0x404719, 0x60, 0x0, 0x0, 0x412545, 0x459b60, 0xc0000001a0, 0x2b, ...)
            	/tmp/stack545513363/main.go:6 +0x27
            main.main()
            	/tmp/stack545513363/main.go:3 +0x56
            exit status 2
    --- FAIL: TestAugment/5-[]interface{} (0.17s)
        source_test.go:552: First
        source_test.go:574: failed to parse input: failed to parse int on line: "main.f({0xc000058760, 0x0, 0x412625})"
    --- FAIL: TestAugment/15-error (0.18s)
        source_test.go:552: First
        source_test.go:574: failed to parse input: failed to parse int on line: "main.f({0x477a40, 0xc00010c000})"
    --- FAIL: TestAugment/3-interface{} (0.12s)
        source_test.go:552: First
        source_test.go:574: failed to parse input: failed to parse int on line: "main.f({0x0, 0x60, 0x7f529a0ed108})"
    --- FAIL: TestAugment/12-string (0.13s)
        source_test.go:552: First
        source_test.go:574: failed to parse input: failed to parse int on line: "main.f({0x4615a1, 0xc0000001a0})"
    --- FAIL: TestAugment/2-func_ellipsis (0.11s)
        source_test.go:552: First
        source_test.go:574: failed to parse input: failed to parse int on line: "main.f({0xc000058768, 0x412545, 0x459b60})"
    --- FAIL: TestAugment/4-[]int (0.14s)
        source_test.go:552: First
        source_test.go:574: failed to parse input: failed to parse int on line: "main.f({0x0, 0xc000058750, 0xc000058770})"
    --- FAIL: TestAugment/16-error_unnamed (0.12s)
        source_test.go:552: First
        source_test.go:574: failed to parse input: failed to parse int on line: "main.f({0x4622a7, 0x3})"
--- FAIL: TestScanSnapshotSyntheticTwoSnapshots (0.51s)
    context_test.go:1231: Goroutine mismatch (-want +got):
          []*stack.Goroutine{
          	&{
          		Signature: stack.Signature{
          			... // 2 identical fields
          			SleepMin: 0,
          			SleepMax: 0,
          			Stack: stack.Stack{
          				Calls: []stack.Call{
          					{
          						Func: {Complete: "main.panicint", ImportPath: "main", DirName: "main", Name: "panicint", ...},
          						Args: stack.Args{
          							Values: []stack.Arg{
          								{
        - 									Value: 42,
        + 									Value: 1,
          									Name:  "",
          									IsPtr: false,
          								},
          							},
          							Processed: nil,
          							Elided:    false,
          						},
          						RemoteSrcPath: "/home/michael/go/src/github.com/maruel/panicparse/cmd/panic/main.go",
          						Line:          89,
          						... // 6 identical fields
          					},
          					{Func: {Complete: "main.glob..func9", ImportPath: "main", DirName: "main", Name: "glob..func9", ...}, RemoteSrcPath: "/home/michael/go/src/github.com/maruel/panicparse/cmd/panic/main.go", Line: 310, SrcName: "main.go", ...},
          					{Func: {Complete: "main.main", ImportPath: "main", DirName: "main", Name: "main", ...}, RemoteSrcPath: "/home/michael/go/src/github.com/maruel/panicparse/cmd/panic/main.go", Line: 72, SrcName: "main.go", ...},
          				},
          				Elided: false,
          			},
          			Locked: false,
          		},
          		ID:    1,
          		First: true,
          		... // 2 identical fields
          	},
          }
--- FAIL: TestPanic (0.51s)
    --- FAIL: TestPanic/str (0.00s)
        context_test.go:1576: failed to parse int on line: "main.panicstr({0x4ba879, 0x1})"
    --- FAIL: TestPanic/slice_str (0.00s)
        context_test.go:1576: failed to parse int on line: "main.panicslicestr({0xc00018a020, 0x1, 0x1})"
    --- FAIL: TestPanic/stdlib (0.00s)
        context_test.go:1576: failed to parse int on line: "strings.FieldsFunc({0x4d84a8, 0x1}, 0x4c2e38)"
    --- FAIL: TestPanic/stdlib_and_other (0.00s)
        context_test.go:1576: failed to parse int on line: "strings.FieldsFunc({0x4d84a8, 0x1}, 0x4c2e50)"
    --- FAIL: TestPanic/utf8 (0.00s)
        context_test.go:1840: Goroutine mismatch (-want +got):
              []*stack.Goroutine{
              	&{
              		Signature: stack.Signature{
              			... // 2 identical fields
              			SleepMin: 0,
              			SleepMax: 0,
              			Stack: stack.Stack{
              				Calls: []stack.Call{
              					{
              						Func: {Complete: "github.com/maruel/panicparse/v2/cmd/panic/internal/utf8.(*Strùc"..., ImportPath: "github.com/maruel/panicparse/v2/cmd/panic/internal/utf8", DirName: "utf8", Name: "(*Strùct).Pànic", ...},
              						Args: stack.Args{
              							Values: []stack.Arg{
              								{
              									Value: 42,
              									Name:  "",
            - 									IsPtr: true,
            + 									IsPtr: false,
              								},
              							},
              							Processed: nil,
              							Elided:    false,
              						},
              						RemoteSrcPath: "/home/michael/go/src/github.com/maruel/panicparse/cmd/panic/inte"...,
              						Line:          42,
              						... // 6 identical fields
              					},
              					{Func: {Complete: "main.glob..func21", ImportPath: "main", DirName: "main", Name: "glob..func21", ...}, RemoteSrcPath: "/home/michael/go/src/github.com/maruel/panicparse/cmd/panic/main.go", Line: 42, SrcName: "main.go", ...},
              					{Func: {Complete: "main.main", ImportPath: "main", DirName: "main", Name: "main", ...}, RemoteSrcPath: "/home/michael/go/src/github.com/maruel/panicparse/cmd/panic/main.go", Line: 42, SrcName: "main.go", ...},
              				},
              				Elided: false,
              			},
              			Locked: false,
              		},
              		ID:    1,
              		First: true,
              		... // 2 identical fields
              	},
              }
    --- FAIL: TestPanic/args_elided (0.00s)
        context_test.go:1630: Goroutine mismatch (-want +got):
              []*stack.Goroutine{
              	&{
              		Signature: stack.Signature{
              			... // 2 identical fields
              			SleepMin: 0,
              			SleepMax: 0,
              			Stack: stack.Stack{
              				Calls: []stack.Call{
              					{
              						Func: {Complete: "main.panicArgsElided", ImportPath: "main", DirName: "main", Name: "panicArgsElided", ...},
              						Args: stack.Args{
              							Values: []stack.Arg{
              								{
              									Value: 42,
              									Name:  "",
            - 									IsPtr: false,
            + 									IsPtr: true,
              								},
              								{
              									Value: 42,
              									Name:  "",
            - 									IsPtr: false,
            + 									IsPtr: true,
              								},
              								{
              									Value: 42,
              									Name:  "",
            - 									IsPtr: false,
            + 									IsPtr: true,
              								},
              								{
              									Value: 42,
              									Name:  "",
            - 									IsPtr: false,
            + 									IsPtr: true,
              								},
              								{
              									Value: 42,
              									Name:  "",
            - 									IsPtr: false,
            + 									IsPtr: true,
              								},
            - 								{Value: 42},
              								{Value: 42},
            + 								{Value: 42, IsPtr: true},
              								{Value: 42},
              								{Value: 42},
              								{Value: 42},
              							},
              							Processed: nil,
            - 							Elided:    true,
            + 							Elided:    false,
              						},
              						RemoteSrcPath: "/home/michael/go/src/github.com/maruel/panicparse/cmd/panic/main.go",
              						Line:          42,
              						... // 6 identical fields
              					},
              					{Func: {Complete: "main.glob..func1", ImportPath: "main", DirName: "main", Name: "glob..func1", ...}, RemoteSrcPath: "/home/michael/go/src/github.com/maruel/panicparse/cmd/panic/main.go", Line: 42, SrcName: "main.go", ...},
              					{Func: {Complete: "main.main", ImportPath: "main", DirName: "main", Name: "main", ...}, RemoteSrcPath: "/home/michael/go/src/github.com/maruel/panicparse/cmd/panic/main.go", Line: 42, SrcName: "main.go", ...},
              				},
              				Elided: false,
              			},
              			Locked: false,
              		},
              		ID:    1,
              		First: true,
              		... // 2 identical fields
              	},
              }
--- FAIL: TestPanicweb (0.53s)
    context_test.go:1853: failed to parse int on line: "net/http.(*Server).Serve(0xc0000a0000, {0x893778, 0xc000126108})"
FAIL	github.com/maruel/panicparse/v2/stack	0.668s
FAIL
```

**Comment by stapelberg** [comment]
Relevant bit of the release notes: https://tip.golang.org/doc/go1.17#compiler

> The format of stack traces from the runtime (printed when an uncaught panic occurs, or when runtime.Stack is called) is improved. Previously, the function arguments were printed as hexadecimal words based on the memory layout. Now each argument in the source code is printed separately, separated by commas. Aggregate-typed (struct, array, string, slice, interface, and complex) arguments are delimited by curly braces. A caveat is that the value of an argument that only lives in a register and is not stored to memory may be inaccurate. Function return values (which were usually inaccurate) are no longer printed.

**Comment by stapelberg** [comment]
Here are a few changes I found necessary, but they don’t fix all the test failures yet (help welcome!):

Remove braces (now used for grouping):

```diff
--- i/stack/context.go
+++ w/stack/context.go
@@ -811,7 +811,9 @@ func parseFunc(c *Call, line []byte) (bool, error) {
                // It is also done in c.init() but do it here in case of a corrupted trace
                // for the file section.
                c.ImportPath = c.Func.ImportPath
-               for _, a := range bytes.Split(match[2], commaSpace) {
+               withoutBraces := bytes.ReplaceAll(match[2], []byte{'{'}, nil)
+               withoutBraces = bytes.ReplaceAll(withoutBraces, []byte{'}'}, nil)
+               for _, a := range bytes.Split(withoutBraces, commaSpace) {
                        if bytes.Equal(a, threeDots) {
                                c.Args.Elided = true
                                continue
```

Update test to cope with more inlining:

```diff
--- i/stack/source_test.go
+++ w/stack/source_test.go
@@ -56,7 +56,7 @@ func TestAugment(t *testing.T) {
                                _ = a(3)
                                panic("ooh")
                        }`,
-                       false,
+                       true,
                        Stack{
                                Calls: []Call{
                                        newCallSrc(
```

Disable optimizations to prevent more inlining:
```diff
@@ -767,7 +767,7 @@ func overrideEnv(env []string, key, value string) []string {
 func getCrash(t *testing.T, main string, disableInline bool) []byte {
        args := []string{"run"}
        if disableInline {
-               args = append(args, "-gcflags", "-l")
+               args = append(args, "-gcflags", "-N -l")
        }
        cmd := exec.Command("go", append(args, main)...)
        // Use the Go 1.4 compatible format.

```

**Comment by maruel** [comment]
Warning: I did a few unrelated changes today, including renaming master to main.

I added -N everywhere.

I did not add the {} zapping as I currently feel it's a hack. I would have preferred for the state machine to be updated but it may not be worth it in the end.

I did not do the source_test.go change because then the test fails on go1.16. I need to improve the test expectations.

**Comment by maruel** [comment]
The CL that changed the format is https://go-review.googlesource.com/c/go/+/304470.

I'll probably have to add more cases to cmd/panic. The example with arrays in the CL description is a good one.

**Comment by stapelberg** [comment]
https://github.com/golang/go/commit/404127c30f3f66eb234da2dc1a78e6eea0ef4ee0 just landed, so we should probably test against go tip instead of the released 1.17 versions.

**Comment by maruel** [comment]
Updated initial comment to include how to build locally.

**Comment by derekperkins** [comment]
Any updates on this? We're blocked on upgrading to 1.17 until this fix lands.

**Comment by maruel** [comment]
The way I see it is:

- `stack.scanningState` need a new field `isGo117 bool`.
- `parsefunc()` would gain 2 new arguments, `firstFunc, isGo117 bool`. The first one would be true as long as `len(Snapshot.Goroutines) == 1 && len(Snapshot.Goroutines[0].Stack.Calls) == 0)` or something like that (need double checking).
- `parsefunc()` would gain a new return value isGo117, that would be true when firstFunc is true and new style is dectected.

Then corresponding unit tests have to be added. This is all located in  https://github.com/maruel/panicparse/blob/main/stack/context.go.

 I welcome everyone to submit a PR for this.
