### ISSUE TITLE
TestAugment/float64 fails on 32-bit architectures (v1.6.1)

### ISSUE THREAD

**Issue by anthonyfok** [maruel/panicparse#65]
The Debian build daemons for 32-bit architectures uncovered an error with TestAugment/float64,
see https://buildd.debian.org/status/package.php?p=panicparse

It was reproducible on my amd64 machine by setting the GOARCH environment variable.

Tested with Go 1.14.7, 1.15.15, 1.16.7, and 1.17.

## 386, arm, and mipsle (with GOMIPS=softfloat)

```
$ GOARCH=386 GOOS=linux go test ./...
?   	github.com/maruel/panicparse	[no test files]
ok  	github.com/maruel/panicparse/cmd/panic	(cached)
?   	github.com/maruel/panicparse/cmd/panic/internal	[no test files]
?   	github.com/maruel/panicparse/cmd/panic/internal/incorrect	[no test files]
?   	github.com/maruel/panicparse/cmd/panic/internal/utf8	[no test files]
?   	github.com/maruel/panicparse/cmd/panicweb	[no test files]
?   	github.com/maruel/panicparse/cmd/panicweb/internal	[no test files]
?   	github.com/maruel/panicparse/cmd/pp	[no test files]
ok  	github.com/maruel/panicparse/internal	(cached)
ok  	github.com/maruel/panicparse/internal/htmlstack	(cached)
?   	github.com/maruel/panicparse/internal/internaltest	[no test files]
compile failure: exit status 2
go build: -race is only supported on linux/amd64, linux/ppc64le, linux/arm64, freebsd/amd64, netbsd/amd64, darwin/amd64, darwin/arm64, and windows/amd64
--- FAIL: TestAugment (0.00s)
    --- FAIL: TestAugment/float64 (0.50s)
        source_test.go:468: Call 0, value 0, expected pointer, got 0
FAIL
FAIL	github.com/maruel/panicparse/stack	4.558s
ok  	github.com/maruel/panicparse/stack/webstack	(cached)
FAIL
```

## mipsle (with GOMIPS=softfloat)

```
$ GOARCH=mips GOMIPS=softfloat go test -run TestAugment ./stack
--- FAIL: TestAugment (0.02s)
    --- FAIL: TestAugment/float64 (0.54s)
        source_test.go:472: Different (-want +got):
              stack.Stack{
              	Calls: []stack.Call{
              		{
              			... // 2 identical fields
              			Line: 6,
              			Func: {Raw: "main.f"},
              			Args: stack.Args{
              				Values: []stack.Arg{
              					{Value: 805306367},
            + 					{},
              				},
              				Processed: nil,
              				Elided:    false,
              			},
              			IsStdlib:   false,
              			RelSrcPath: "",
              		},
              		{SrcPath: "main.go", Line: 3, Func: {Raw: "main.main"}},
              	},
              	Elided: false,
              }
        source_test.go:473: Source code:
            package main
            func main() {
            	f(0.5)
            }
            func f(v float64) {
            	panic("ooh")
            }
        source_test.go:474: Output:
            panic: ooh
            
            goroutine 1 [running]:
            main.f(0x3fe00000, 0x0)
            	/tmp/panicparse297691722/main.go:6 +0x4c
            main.main()
            	/tmp/panicparse297691722/main.go:3 +0x40
            exit status 2
FAIL
FAIL	github.com/maruel/panicparse/stack	4.241s
FAIL
```

Thanks in advance!

**Comment by anthonyfok** [comment]
Hi again,

Now that I have prepared the workaround for the panicparse 1.6.1-2 Debian package, I now realize the float64nan fatal error is a separate issue that can be circumvented by `GOMIPS=softfloat`, or perhaps it is machine-dependent, so I have separated that out into Issue #67.

Here is my patch to skip TestAugment/float64 on 32-bit architectures to avoid build failures on Debian's armel, armhf, i386 and mipsel build daemons at https://buildd.debian.org/status/package.php?p=panicparse:

```patch
Description: Skip TestAugment/float64 on 32-bit architectures
 Skip TestAugment/float64 on 386, arm, mips and mipsle to avoid errors.
 .
 mips and mipsle also require GOMIPS=softfloat to circumvent
     fatal error: float64nan
     runtime: panic before malloc heap initialized
Author: Anthony Fok <foka@debian.org>
Origin: vendor
Bug: https://github.com/maruel/panicparse/issues/65
Last-Update: 2021-09-10
---
This patch header follows DEP-3: http://dep.debian.net/deps/dep3/
--- a/stack/source_test.go
+++ b/stack/source_test.go
@@ -11,6 +11,7 @@
 	"os"
 	"os/exec"
 	"path/filepath"
+	"runtime"
 	"strings"
 	"testing"
 
@@ -472,7 +473,12 @@
 				t.Logf("Different (-want +got):\n%s", diff)
 				t.Logf("Source code:\n%s", input)
 				t.Logf("Output:\n%s", content)
-				t.FailNow()
+				arch := runtime.GOARCH
+				if t.Name() == "TestAugment/float64" && arch == "mips" {
+					t.Logf("Allow %s difference on %s\nSee https://github.com/maruel/panicparse/issues/65\n", t.Name(), arch)
+				} else {
+					t.FailNow()
+				}
 			}
 
 			// If inlining was disabled, try a second time but zap things out.
@@ -624,6 +630,14 @@
 			if want.Calls[i].Args.Values[j].Value == pointer {
 				// Replace the pointer value.
 				if got.Calls[i].Args.Values[j].Value == 0 {
+					if t.Name() == "TestAugment/float64" {
+						switch arch := runtime.GOARCH; arch {
+						case "386", "arm", "mipsle":
+							t.Logf("Call %d, value %d, expected pointer, got 0", i, j)
+
+							t.Skipf("Skipping %s on %s\nSee https://github.com/maruel/panicparse/issues/65\n", t.Name(), arch)
+						}
+					}
 					t.Fatalf("Call %d, value %d, expected pointer, got 0", i, j)
 				}
 				old := fmt.Sprintf("0x%x", got.Calls[i].Args.Values[j].Value)
```

**Comment by maruel** [comment]
Thanks for the report!

Indeed `GOARCH=386 go test ./stack` is particularly borked, more than just float64. Will try to address this fully.

**Comment by maruel** [comment]
Adding a workflow to test base 32 bits functionality in https://github.com/maruel/panicparse/commit/87b56f309b091e45cf1b75e54c7b240fb507293b shows the current failures inside github actions: https://github.com/maruel/panicparse/runs/3575259316

As issues gets fixed, I plan to enforce this to catch regressions.
